### ISSUE TITLE
English version has no "Unit test" segment.

### ISSUE THREAD

**Issue by seaward** [alibaba/p3c#834]
Can you help to add it?

**Comment by xuantan** [comment]
@dyrone 看下

**Comment by dyrone** [comment]
@seaward 

Thanks for the feedback about the English version of the Java guidelines.

Firstly, I try to understand your subject of this PR, do you mean that the English version does not have a section (the word "segment" you specify here) about the "Unit Tests".

If we are on the same page, actually, we have a long-tail plan for the English version to catch up because it had been a far-away distance from the current Chinese main version.

Or we will be appreciated that if you're willing to contribute to this :)

Thanks.
